version: "3.7"
services:
  web:
#    image: php:8.0-apache
    build:
      ./docker-compose/php
    working_dir: /var/www/html/
    ports:
      - 8080:80
    volumes:
      - ./newlara:/var/www/html
    security_opt:
      - seccomp:unconfined
    networks:
      - lara8

  db:
    image: mysql:5.7
    container_name: lara8-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - lara8

  phpmyadmin:
    image: phpmyadmin
    container_name: lara8dock-phpadmin
    restart: always
    ports:
      - 8090:80
    networks:
      - lara8

networks:
  lara8:
    driver: bridge